import "./globals.css";
import { Poppins } from "next/font/google";

import type { Metadata } from "next";
import { Header } from "./_components/header";
import { Footer } from "./_components/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactNode {
  return (
    <html lang="en">
      <body>
        <main className={`${poppins.className} font-sans font-normal`}>
          <div className="flex min-h-screen w-full flex-col items-center">
            <Header />
            {children}
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
